# default build for all distros
# only create artifacts of the build directory when something fails (for cmake logs)
# cache the ccache/ directory for each job separately
.build_template: &distro_build
  before_script:
    - ci/install_dependencies.sh
  script:
    - python3 ci/test_build.py
  artifacts:
    when: on_failure
    paths:
      - build/
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - ccache/

stages:
  - test
  - deploy

Fedora:
  image: fedora:28
  <<: *distro_build

Debian:
  image: debian:9
  <<: *distro_build

Archlinux:
  image: base/archlinux
  <<: *distro_build

Ubuntu:
  image: ubuntu:18.04
  <<: *distro_build

CentOS:
  image: centos:7
  <<: *distro_build

OpenSUSE:
  image: opensuse:tumbleweed
  <<: *distro_build

Install:
  image: fedora:28
  stage: deploy
  before_script:
    - ci/install_dependencies.sh
  script:
    - mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=Release -DEXIV2_ENABLE_VIDEO=ON -DEXIV2_ENABLE_WEBREADY=ON -DEXIV2_BUILD_UNIT_TESTS=ON -DCMAKE_INSTALL_PREFIX=/usr/ -DBUILD_WITH_CCACHE=ON ..
    - make -j $(nproc)
    - make install
    - make clean
    - EXIV2_BINDIR=/usr/bin/ make tests
