language: cpp

git:
  quiet: true
  depth: 1

env:
  global:
    - COMMON_CMAKE_OPTIONS="-DEXIV2_ENABLE_WEBREADY=ON -DEXIV2_ENABLE_CURL=ON -DEXIV2_BUILD_UNIT_TESTS=ON -DEXIV2_ENABLE_BMFF=ON -DEXIV2_TEAM_WARNINGS_AS_ERRORS=ON -DCMAKE_INSTALL_PREFIX=install"

matrix:
  include:
    - name: "Ubuntu 18.04 - gcc (Release)"
      os: linux
      dist: bionic
      sudo: required
      compiler: gcc
      env:
        - BUILD_TYPE="Release"

    - name: "Ubuntu 18.04 - gcc (Debug)"
      os: linux
      dist: bionic
      sudo: required
      compiler: gcc
      env:
        - BUILD_TYPE="Debug"

    - name: "Ubuntu 20.04 - gcc (Release)"
      os: linux
      dist: focal
      sudo: required
      compiler: gcc
      env:
        - BUILD_TYPE="Release"

    - name: "Ubuntu 20.04 - gcc (Debug)"
      os: linux
      dist: focal
      sudo: required
      compiler: gcc
      env:
        - BUILD_TYPE="Debug"

    - name: "macOS 10.14 - XCode 11.3"
      os: osx
      osx_image: xcode11.3
      compiler: clang
      env:
        - BUILD_TYPE="Release"

install: ./ci/install.sh
script:  ./ci/run.sh

cache:
    ccache: true
    directories:
    - conan         # Conan installation folder
    - $HOME/conanData     # Conan storage location
