language: cpp

sudo: required

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

env:
  - CMAKE_OPTIONS="" # Default 
  - CMAKE_OPTIONS="-DEXIV2_ENABLE_VIDEO=ON -DEXIV2_ENABLE_WEBREADY=ON" # All enabled
  - CMAKE_OPTIONS="-DEXIV2_ENABLE_XMP=OFF -DEXIV2_ENABLE_NLS=OFF -DEXIV2_ENABLE_LENSDATA=OFF" # All disabled
  - CMAKE_OPTIONS="-DEXIV2_ENABLE_WEBREADY=ON -DEXIV2_ENABLE_CURL=OFF -DEXIV2_ENABLE_SSH=OFF" # WebReady without SSH nor CURL
    

install: ./.travis/install.sh
script:  ./.travis/run.sh
